create table if not exists ce_company (
    id bigint generated by default as identity primary key,
    external_tenant_id varchar(120) unique,
    legal_name varchar(180) not null,
    trade_name varchar(180) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists ce_user_account (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    external_user_id varchar(120),
    full_name varchar(180) not null,
    email varchar(180) not null,
    status varchar(30) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    constraint fk_ce_user_company foreign key (company_id) references ce_company (id),
    constraint uq_ce_user_email_company unique (company_id, email)
);

create table if not exists ce_role (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name varchar(120) not null
);

create table if not exists ce_user_role (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_ce_user_role_user foreign key (user_id) references ce_user_account (id),
    constraint fk_ce_user_role_role foreign key (role_id) references ce_role (id)
);

create table if not exists ce_cost_center (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    code varchar(60) not null,
    name varchar(160) not null,
    constraint fk_ce_cost_center_company foreign key (company_id) references ce_company (id),
    constraint uq_ce_cost_center unique (company_id, code)
);

create table if not exists ce_expense_category (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    code varchar(60) not null,
    name varchar(160) not null,
    parent_category_id bigint,
    constraint fk_ce_expense_category_company foreign key (company_id) references ce_company (id),
    constraint fk_ce_expense_category_parent foreign key (parent_category_id) references ce_expense_category (id),
    constraint uq_ce_expense_category unique (company_id, code)
);

create table if not exists ce_budget_cycle (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    reference_month date not null,
    status varchar(30) not null default 'OPEN',
    closed_at timestamp,
    closed_by varchar(120),
    constraint fk_ce_budget_cycle_company foreign key (company_id) references ce_company (id),
    constraint uq_ce_budget_cycle unique (company_id, reference_month)
);

create table if not exists ce_budget_line (
    id bigint generated by default as identity primary key,
    budget_cycle_id bigint not null,
    cost_center_id bigint not null,
    expense_category_id bigint not null,
    planned_amount decimal(15, 2) not null,
    constraint fk_ce_budget_line_cycle foreign key (budget_cycle_id) references ce_budget_cycle (id),
    constraint fk_ce_budget_line_cost_center foreign key (cost_center_id) references ce_cost_center (id),
    constraint fk_ce_budget_line_category foreign key (expense_category_id) references ce_expense_category (id),
    constraint uq_ce_budget_line unique (budget_cycle_id, cost_center_id, expense_category_id)
);

create table if not exists ce_expense (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    budget_cycle_id bigint,
    cost_center_id bigint,
    expense_category_id bigint,
    user_account_id bigint,
    external_expense_id varchar(120),
    description varchar(255) not null,
    amount decimal(15, 2) not null,
    occurred_on date not null,
    status varchar(30) not null default 'POSTED',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_ce_expense_company foreign key (company_id) references ce_company (id),
    constraint fk_ce_expense_cycle foreign key (budget_cycle_id) references ce_budget_cycle (id),
    constraint fk_ce_expense_cost_center foreign key (cost_center_id) references ce_cost_center (id),
    constraint fk_ce_expense_category foreign key (expense_category_id) references ce_expense_category (id),
    constraint fk_ce_expense_user foreign key (user_account_id) references ce_user_account (id)
);

create table if not exists ce_payment (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    expense_id bigint,
    external_payment_id varchar(120),
    payment_method varchar(40) not null,
    amount decimal(15, 2) not null,
    status varchar(30) not null default 'PENDING',
    paid_at timestamp,
    created_at timestamp not null default current_timestamp,
    constraint fk_ce_payment_company foreign key (company_id) references ce_company (id),
    constraint fk_ce_payment_expense foreign key (expense_id) references ce_expense (id)
);

create table if not exists ce_agent_job (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    agent_type varchar(80) not null,
    payload_json clob,
    status varchar(30) not null default 'QUEUED',
    requested_at timestamp not null default current_timestamp,
    finished_at timestamp,
    constraint fk_ce_agent_job_company foreign key (company_id) references ce_company (id)
);

create table if not exists ce_audit_log (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    entity_type varchar(80) not null,
    entity_id varchar(120),
    action varchar(40) not null,
    detail varchar(255),
    created_at timestamp not null default current_timestamp,
    constraint fk_ce_audit_company foreign key (company_id) references ce_company (id)
);

create or replace view ce_v_budget_execution as
select bc.reference_month,
       bc.company_id,
       bc.id as budget_cycle_id,
       cc.id as cost_center_id,
       ec.id as expense_category_id,
       sum(bl.planned_amount) as planned_amount,
       coalesce(sum(e.amount), 0) as executed_amount,
       sum(bl.planned_amount) - coalesce(sum(e.amount), 0) as remaining_amount
  from ce_budget_line bl
  join ce_budget_cycle bc on bc.id = bl.budget_cycle_id
  join ce_cost_center cc on cc.id = bl.cost_center_id
  join ce_expense_category ec on ec.id = bl.expense_category_id
  left join ce_expense e on e.budget_cycle_id = bc.id
                        and e.cost_center_id = cc.id
                        and e.expense_category_id = ec.id
                        and e.status = 'POSTED'
 group by bc.reference_month, bc.company_id, bc.id, cc.id, ec.id;

create or replace view ce_v_payment_summary as
select bc.reference_month,
       p.company_id,
       count(*) as payment_count,
       sum(p.amount) as total_amount,
       sum(case when p.status = 'PAID' then p.amount else 0 end) as paid_amount,
       sum(case when p.status <> 'PAID' then p.amount else 0 end) as pending_amount
  from ce_payment p
  join ce_expense e on e.id = p.expense_id and e.status = 'POSTED'
  join ce_budget_cycle bc on bc.id = e.budget_cycle_id
 group by bc.reference_month, p.company_id;

merge into ce_role (code, name) key(code) values
('ADMIN', 'Administrador ERP'),
('ANALYST', 'Analista ERP'),
('APPROVER', 'Aprovador ERP');

create alias if not exists ERP_CLOSE_BUDGET_CYCLE for "com.spacecworp.fintechapi.cloudengine.infrastructure.jdbc.CloudEngineProcedures.closeBudgetCycle";
create alias if not exists ERP_REGISTER_AGENT_JOB for "com.spacecworp.fintechapi.cloudengine.infrastructure.jdbc.CloudEngineProcedures.registerAgentJob";

create trigger if not exists ce_expense_audit_trigger
after insert, update, delete on ce_expense
for each row call "com.spacecworp.fintechapi.cloudengine.infrastructure.jdbc.CloudEngineAuditTrigger";

create trigger if not exists ce_payment_audit_trigger
after insert, update, delete on ce_payment
for each row call "com.spacecworp.fintechapi.cloudengine.infrastructure.jdbc.CloudEngineAuditTrigger";
