spring.application.name=fintech-api
server.port=${PORT:8080}
app.jwt.secret=${APP_JWT_SECRET:change-me-in-prod-with-a-long-random-secret-value-1234567890}
app.jwt.ttl-seconds=3600
logging.level.root=INFO
logging.level.com.spacecworp.fintechapi=INFO
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:cloud-engine;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:db/migration
