spring.application.name=fintech-api
server.port=8080
app.jwt.secret=${APP_JWT_SECRET:change-me-in-prod-with-a-long-random-secret-value-1234567890}
app.jwt.ttl-seconds=3600
logging.level.root=INFO
logging.level.com.spacecworp.fintechapi=INFO
